apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: root-health
  namespace: gateway-system
spec:
  parentRefs:
    - name: edge
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /healthz
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Content-Length
                value: "0"
      backendRefs: []        # direct-response; no service needed
